# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9HapczqgdYEsPATjaV3WC4uQZ1pPG1C
"""

from scipy.io import loadmat
import matplotlib.pyplot as plt
import numpy as np
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold, cross_val_predict
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_curve, auc, precision_recall_curve, confusion_matrix, cohen_kappa_score, matthews_corrcoef
from sklearn.utils import shuffle
from scipy.stats import skew, kurtosis
from sklearn.preprocessing import label_binarize
import xgboost as xgb
from sklearn.ensemble import VotingClassifier
import shap

# Load data and ensure all datasets have the same length
def load_and_trim_data(paths):
    data = [loadmat(path)['linear_envelope'].flatten() for path, _ in paths]
    min_length = min(len(d) for d in data)
    return [d[:min_length] for d in data], min_length

# Extract features from epoch data
def extract_features(epoch_data, fs):
    return [
        np.var(epoch_data), np.max(epoch_data), skew(epoch_data),
        kurtosis(epoch_data), np.sqrt(np.mean(epoch_data**2)),
        np.mean(np.abs(epoch_data)), np.trapz(epoch_data, dx=1/fs),
        np.sum(epoch_data > 0.002 * np.max(epoch_data))
    ]

# Plot epochs
def plot_epochs(epochs, title_prefix):
    plt.figure(figsize=(12, 12))
    for i, epoch in enumerate(epochs[:6]):
        plt.subplot(6, 1, i+1)
        plt.plot(epoch)
        plt.title(f'{title_prefix} Epoch {i+1}')
        plt.xlabel('Sample')
        plt.ylabel('amp')
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(12, 12))
    for i, epoch in enumerate(epochs[6:]):
        plt.subplot(6, 1, i+1)
        plt.plot(epoch)
        plt.title(f'{title_prefix} Epoch {i+7}')
        plt.xlabel('Sample')
        plt.ylabel('amp')
    plt.tight_layout()
    plt.show()

# Plot training epochs
def plot_training_epochs(epochs, title_prefix):
    plt.figure(figsize=(12, 12))
    for i, epoch in enumerate(epochs[:5]):
        plt.subplot(5, 1, i+1)
        plt.plot(epoch)
        plt.title(f'{title_prefix} Training Epoch {i+1}')
        plt.xlabel('Sample')
        plt.ylabel('amp')
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(12, 12))
    for i, epoch in enumerate(epochs[5:]):
        plt.subplot(5, 1, i+1)
        plt.plot(epoch)
        plt.title(f'{title_prefix} Training Epoch {i+6}')
        plt.xlabel('Sample')
        plt.ylabel('amp')
    plt.tight_layout()
    plt.show()

# Train and evaluate model
def train_and_evaluate_model(model, model_name, X_train, Y_train, X_test, Y_test):
    model.fit(X_train, Y_train)
    Y_pred = model.predict(X_test)
    accuracy = accuracy_score(Y_test, Y_pred) * 100
    precision = precision_score(Y_test, Y_pred, average='weighted') * 100
    recall = recall_score(Y_test, Y_pred, average='weighted') * 100
    f1 = f1_score(Y_test, Y_pred, average='weighted') * 100
    kappa = cohen_kappa_score(Y_test, Y_pred) * 100
    mcc = matthews_corrcoef(Y_test, Y_pred) * 100
    conf_matrix = confusion_matrix(Y_test, Y_pred)

    print(f"{model_name} Confusion Matrix:\n{conf_matrix}")
    print(f"{model_name} Cohen’s Kappa: {kappa:.2f}%")
    print(f"{model_name} Matthews Correlation Coefficient (MCC): {mcc:.2f}%")

    # Binarize the output
    Y_test_bin = label_binarize(Y_test, classes=[0, 1, 2])
    Y_pred_bin = label_binarize(Y_pred, classes=[0, 1, 2])

    # Compute ROC curve and ROC area for each class
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(3):
        fpr[i], tpr[i], _ = roc_curve(Y_test_bin[:, i], model.predict_proba(X_test)[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    # Plot ROC curve
    plt.figure()
    for i, disease in enumerate(['Healthy', 'Neuropathy', 'Myopathy']):
        plt.plot(fpr[i], tpr[i], lw=2, label=f'{disease} ROC curve (area = {roc_auc[i]:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'{model_name} ROC Curve')
    plt.legend(loc="lower right")
    plt.show()

    # Compute precision-recall curve and area for each class
    precision_dict = dict()
    recall_dict = dict()
    pr_auc = dict()
    for i in range(3):
        precision_dict[i], recall_dict[i], _ = precision_recall_curve(Y_test_bin[:, i], model.predict_proba(X_test)[:, i])
        pr_auc[i] = auc(recall_dict[i], precision_dict[i])

    # Plot Precision-Recall curve
    plt.figure()
    for i, disease in enumerate(['Healthy', 'Neuropathy', 'Myopathy']):
        plt.plot(recall_dict[i], precision_dict[i], lw=2, label=f'{disease} Precision-Recall curve (area = {pr_auc[i]:.2f})')
        plt.xlabel('Recall')
        plt.ylabel('Precision')
        plt.title(f'{model_name} Precision-Recall Curve')
        plt.legend(loc="lower left")
        plt.show()

    # Cross-validation
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    y_pred_cv = cross_val_predict(model, X_train, Y_train, cv=kfold)
    accuracy_cv = accuracy_score(Y_train, y_pred_cv) * 100
    print(f"Cross-Validation Accuracy ({model_name}): {accuracy_cv:.2f}%")

    return accuracy, precision, recall, f1, kappa, mcc

# Visualize extracted features
def visualize_features(X, Y, feature_names):
    fig, axes = plt.subplots(1, len(feature_names), figsize=(20, 5))
    colors = ['r', 'g', 'b']
    labels = ['Healthy', 'Neuropathy', 'Myopathy']
    for i, ax in enumerate(axes):
        for label, color in zip(np.unique(Y), colors):
            ax.scatter(np.arange(len(X[Y == label, i])), X[Y == label, i], c=color, label=labels[int(label)])
        ax.set_title(f'{feature_names[i]} Values')
        ax.set_xlabel('Sample Index')
        ax.set_ylabel(feature_names[i])
    plt.legend()
    plt.tight_layout()
    plt.show()

# Main script
paths = [
    (r"D:\Rafsun\bin\signal project\linear_envelope_neuropathy.mat", 'linear_envelope'),
    (r"D:\Rafsun\bin\signal project\linear_envelope_healthy.mat", 'linear_envelope'),
    (r"D:\Rafsun\bin\signal project\linear_envelope_myopathy.mat", 'linear_envelope')
]

data, min_length = load_and_trim_data(paths)

linear_envelope_neuropathy, linear_envelope_healthy, linear_envelope_myopathy = data

# Given values
total_time, num_epochs = 12, 12
samples_per_epoch = int(min_length / num_epochs)
fs = min_length / total_time

# Segment the dataset into epochs
epochs_neuropathy = [linear_envelope_neuropathy[i * samples_per_epoch:(i + 1) * samples_per_epoch] for i in range(num_epochs)]
epochs_healthy = [linear_envelope_healthy[i * samples_per_epoch:(i + 1) * samples_per_epoch] for i in range(num_epochs)]
epochs_myopathy = [linear_envelope_myopathy[i * samples_per_epoch:(i + 1) * samples_per_epoch] for i in range(num_epochs)]

# Plot segmented epochs
plot_epochs(epochs_neuropathy, 'Neuropathy')
plot_epochs(epochs_healthy, 'Healthy')
plot_epochs(epochs_myopathy, 'Myopathy')

# Training and testing data
num_epochs_to_train = 10
training_epochs_neuropathy = epochs_neuropathy[:num_epochs_to_train]
training_epochs_healthy = epochs_healthy[:num_epochs_to_train]
training_epochs_myopathy = epochs_myopathy[:num_epochs_to_train]
testing_epochs_neuropathy = epochs_neuropathy[num_epochs_to_train:]
testing_epochs_healthy = epochs_healthy[num_epochs_to_train:]
testing_epochs_myopathy = epochs_myopathy[num_epochs_to_train:]

# Plot training and testing epochs
plot_training_epochs(training_epochs_neuropathy, 'Neuropathy')
plot_training_epochs(training_epochs_healthy, 'Healthy')
plot_training_epochs(training_epochs_myopathy, 'Myopathy')

# Initialize arrays to store features
num_features = 8
X_train = np.zeros((3 * num_epochs_to_train, num_features))
Y_train = np.zeros((3 * num_epochs_to_train,))
X_test = np.zeros((6, num_features))
Y_test = np.zeros((6,))

# Extract features for training data
for i in range(num_epochs_to_train):
    X_train[i, :] = extract_features(training_epochs_healthy[i], fs)
    Y_train[i] = 0  # Label for healthy
    X_train[i + num_epochs_to_train, :] = extract_features(training_epochs_neuropathy[i], fs)
    Y_train[i + num_epochs_to_train] = 1  # Label for neuropathy
    X_train[i + 2 * num_epochs_to_train, :] = extract_features(training_epochs_myopathy[i], fs)
    Y_train[i + 2 * num_epochs_to_train] = 2  # Label for myopathy

# Extract features for testing data
for i in range(2):
    X_test[i, :] = extract_features(testing_epochs_healthy[i], fs)
    Y_test[i] = 0  # Label for healthy
    X_test[i + 2, :] = extract_features(testing_epochs_neuropathy[i], fs)
    Y_test[i + 2] = 1  # Label for neuropathy
    X_test[i + 4, :] = extract_features(testing_epochs_myopathy[i], fs)
    Y_test[i + 4] = 2  # Label for myopathy

feature_names = ['Variance', 'Maximum', 'Skewness', 'Kurtosis', 'RMS', 'ARV', 'Integration', 'Total Peak']
visualize_features(X_train, Y_train, feature_names)
visualize_features(X_test, Y_test, feature_names)

# Shuffle training data
X_train, Y_train = shuffle(X_train, Y_train, random_state=42)

# Train and evaluate models
svm_model = SVC(kernel='linear', probability=True)
accuracy_svm, precision_svm, recall_svm, f1_svm, kappa_svm, mcc_svm = train_and_evaluate_model(svm_model, 'SVM', X_train, Y_train, X_test, Y_test)

knn_model = KNeighborsClassifier(n_neighbors=5)
accuracy_knn, precision_knn, recall_knn, f1_knn, kappa_knn, mcc_knn = train_and_evaluate_model(knn_model, 'kNN', X_train, Y_train, X_test, Y_test)

xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
accuracy_xgb, precision_xgb, recall_xgb, f1_xgb, kappa_xgb, mcc_xgb = train_and_evaluate_model(xgb_model, 'XGBoost', X_train, Y_train, X_test, Y_test)

# Ensemble methods
voting_clf = VotingClassifier(estimators=[
    ('svm', svm_model),
    ('knn', knn_model),
    ('xgb', xgb_model)
], voting='soft')
accuracy_vote, precision_vote, recall_vote, f1_vote, kappa_vote, mcc_vote = train_and_evaluate_model(voting_clf, 'Voting Classifier', X_train, Y_train, X_test, Y_test)

# Print performance comparison
print("Performance Comparison after Shuffling:")
print(f"SVM - Accuracy: {accuracy_svm:.2f}%, Precision: {precision_svm:.2f}%, Recall: {recall_svm:.2f}%, F1 Score: {f1_svm:.2f}%, Kappa: {kappa_svm:.2f}%, MCC: {mcc_svm:.2f}%")
print(f"kNN - Accuracy: {accuracy_knn:.2f}%, Precision: {precision_knn:.2f}%, Recall: {recall_knn:.2f}%, F1 Score: {f1_knn:.2f}%, Kappa: {kappa_knn:.2f}%, MCC: {mcc_knn:.2f}%")
print(f"XGBoost - Accuracy: {accuracy_xgb:.2f}%, Precision: {precision_xgb:.2f}%, Recall: {recall_xgb:.2f}%, F1 Score: {f1_xgb:.2f}%, Kappa: {kappa_xgb:.2f}%, MCC: {mcc_xgb:.2f}%")
print(f"Voting Classifier - Accuracy: {accuracy_vote:.2f}%, Precision: {precision_vote:.2f}%, Recall: {recall_vote:.2f}%, F1 Score: {f1_vote:.2f}%, Kappa: {kappa_vote:.2f}%, MCC: {mcc_vote:.2f}%")

# Check for data leakage by ensuring no overlap in training and testing data
print("Training data shape (X_train):", X_train.shape)
print("Testing data shape (X_test):", X_test.shape)